version: "3.8"

services:
  api-gateway:
    image: abdabughazale7/api-gateway-service:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  auth-service:
    image: abdabughazale7/auth-service:latest
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  driver-service:
    image: abdabughazale7/driver-service:latest
    container_name: driver-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - API_GATEWAY_URL=http://api-gateway:8080
      - AUTH_SERVICE_URL=http://auth-service:8081
    depends_on:
      - api-gateway
      - auth-service
    networks:
      - app-network

  ride-service:
    image: abdabughazale7/ride-service:latest
    container_name: ride-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - API_GATEWAY_URL=http://api-gateway:8080
      - AUTH_SERVICE_URL=http://auth-service:8081
    depends_on:
      - api-gateway
      - auth-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
