server:
  port: 8086
  servlet:
    context-path: /api
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: driver-service
          uri: http://driver-service:8081
          predicates:
            - Path=/driver-service/**

        - id: ride-service
          uri: http://ride-service:8085
          predicates:
            - Path=/ride-service/rider/signup

        - id: ride-service-secured
          uri: http://ride-service:8085
          predicates:
            - Path=/ride-service/ride/**
          filters:
            - name: JwtAuthFilter


        - id: author-service
          uri: http://auth-service:8080
          predicates:
            - Path=/author/**
secured:
  sec: "Asaaa51asf1gds1ASGF51ASDG5ad1g8sdag4158A1DSG85A1SD51asg"
