server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: driver-management
          uri: http://localhost:8081
          predicates:
            - Path=/driver-management/**
        - id: ride-booking-management
          uri: http://localhost:8082
          predicates:
            - Path=/rbm/**
