spring:
  application:
    name: driver-management
  datasource:
    url: jdbc:postgresql://localhost:5432/ride-sharing
    username: postgres
    password: 379155
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

rabbitmq:
  queues:
    request-ride: ride.requested
    cancel-ride: ride.canceled
  exchange:
    name: ride.topic
  routing:
    accept-key: ride.accepted
    complete-key: ride.completed
server:
  port: 8081
  servlet:
    context-path: /driver-service
springdoc:
  api-docs:
    path: /api-docs
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    rabbit:
      enabled: true
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10000ms
      permittedNumberOfCallsInHalfOpenState: 3
      minimumNumberOfCalls: 5
      eventConsumerBufferSize: 10
secured:
  key: Asaaa51asf1gds1ASGF51ASDG5ad1g8sdag4158A1DSG85A1SD51asg