--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1
-- Dumped by pg_dump version 17.3

-- Started on 2025-03-08 14:21:41

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 9 (class 2615 OID 24653)
-- Name: ride_management; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA ride_management;


ALTER SCHEMA ride_management OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 229 (class 1259 OID 24693)
-- Name: ride; Type: TABLE; Schema: ride_management; Owner: postgres
--

CREATE TABLE ride_management.ride (
    ride_id bigint NOT NULL,
    amount numeric(38,2),
    created_at timestamp(6) without time zone,
    driver character varying(255),
    driver_mobile_no character varying(255),
    drop_at character varying(255),
    located_at character varying(255),
    mobile_no character varying(255),
    name character varying(255),
    status character varying(255),
    transaction_no character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    username character varying(255),
    CONSTRAINT ride_status_check CHECK (((status)::text = ANY ((ARRAY['REQUESTED'::character varying, 'COMPLETED'::character varying, 'IN_PROGRESS'::character varying, 'PAYMENT_FAILED'::character varying, 'CANCELED'::character varying])::text[])))
);


ALTER TABLE ride_management.ride OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 24692)
-- Name: ride_ride_id_seq; Type: SEQUENCE; Schema: ride_management; Owner: postgres
--

ALTER TABLE ride_management.ride ALTER COLUMN ride_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ride_management.ride_ride_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 24685)
-- Name: riders; Type: TABLE; Schema: ride_management; Owner: postgres
--

CREATE TABLE ride_management.riders (
    rider_id bigint NOT NULL,
    mobile_no character varying(255),
    name character varying(255),
    username character varying(255)
);


ALTER TABLE ride_management.riders OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 24684)
-- Name: riders_rider_id_seq; Type: SEQUENCE; Schema: ride_management; Owner: postgres
--

ALTER TABLE ride_management.riders ALTER COLUMN rider_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ride_management.riders_rider_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3210 (class 2606 OID 24700)
-- Name: ride ride_pkey; Type: CONSTRAINT; Schema: ride_management; Owner: postgres
--

ALTER TABLE ONLY ride_management.ride
    ADD CONSTRAINT ride_pkey PRIMARY KEY (ride_id);


--
-- TOC entry 3208 (class 2606 OID 24691)
-- Name: riders riders_pkey; Type: CONSTRAINT; Schema: ride_management; Owner: postgres
--

ALTER TABLE ONLY ride_management.riders
    ADD CONSTRAINT riders_pkey PRIMARY KEY (rider_id);


--
-- TOC entry 3212 (class 2606 OID 24702)
-- Name: ride uk94sc78xa29kyuvgus1ha5mhi6; Type: CONSTRAINT; Schema: ride_management; Owner: postgres
--

ALTER TABLE ONLY ride_management.ride
    ADD CONSTRAINT uk94sc78xa29kyuvgus1ha5mhi6 UNIQUE (transaction_no);


-- Completed on 2025-03-08 14:21:41

--
-- PostgreSQL database dump complete
--

